Exercício 1

In [3]:
# Usando NumPy, importe o dataset iris mantendo o seu conteúdo intacto.

import numpy as np

iris_dataset_url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
colunas = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii')

sepallength = iris[:,0].astype(float)
sepalwidth = iris[:,1].astype(float)
petallength = iris[:,2].astype(float)
petalwidth = iris[:,3].astype(float)
species = iris[:,4].astype(str)
species


array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [4]:
#Calcule a média, mediana e desvio padrão da primeira coluna (sepallength) do dataset Iris.

import numpy as np

iris_dataset_url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
colunas = ('sepallength','sepalwidth','petallength','species')
iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii')

media=np.median(sepallength)
mediana=np.mean(sepallength)

print(media,mediana)



5.8 5.843333333333334


In [5]:
# 5. Normalize a coluna (sepallength) do dataset iris de tal forma que o valor mínimo seja zero (0) e o valor máximo seja 1.

sepal_length_max=sepallength.max()
sepal_length_min=sepallength.min()

sepallength_normalizada=(sepallength - sepal_length_min) / (sepal_length_max - sepal_length_min)

print(sepallength[:2])
print(sepallength_normalizada[:2])


[5.1 4.9]
[0.22222222 0.16666667]


In [6]:
# 6.Encontre o 5º e o 95º percentil do comprimento das pétalas (sepallength) do dataset Iris

np.percentile(sepallength, q=[5,95])



array([4.6  , 7.255])

In [10]:
# Encontre a quantidade de valores ausentes, bem como a posição deles da primeira coluna da coluna comprimento das pétalas
# (sepallength), dentro do vetor abaixo:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float',usecols=(0,1,2,3),encoding='ascii')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print('Quantidade de dados ausentes:', np.isnan(iris_2d[:,0]).sum())
print('Posição dos valores ausentes:', np.where(np.isnan(iris_2d[:,0])))


Quantidade de dados ausentes: 5
Posição dos valores ausentes: (array([ 36,  59, 113, 140, 141], dtype=int64),)


In [11]:
# Filtre o vetor iris_2d do exercício anterior para que ele tenha: (terceira coluna (petallength) > 1.5) && 
# (primeira coluna (sepallength) < 5.0)

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

condicao=(iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0)
iris_2d[condicao]



array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [15]:
# Selecione as linhas do vetor iris_2d que não contenham valores nan (Not a Number).

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

any_nan_in_row=np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]




array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])